feat: add starlark documentation
konveyor/move2kube-website pull request #99
Opened 2022-11-08 11:17 UTC by kmehant

Signed-off-by: Mehant Kammakomati <kmehant@gmail.com>

2022-11-13 14:37 UTC, ashokponkumar requested changes

2022-11-13 14:37 UTC, ashokponkumar commented on docs/transformers/external/starlark.md
> +* `base_directory_detect()`, `directory_detect()`, `transform()` - These functions are used for Move2Kube transformtion and details can be found [here](https://move2kube.konveyor.io/concepts/transfor
```suggestion
* `directory_detect()`, `transform()` - These functions are used for Move2Kube transformtion and details can be found [here](https://move2kube.konveyor.io/concepts/transformer#methods).
```

2022-11-13 14:37 UTC, ashokponkumar commented on docs/transformers/external/starlark.md
> +
Adding a preamble about custom functions which can be used to achieve certain tasks might help users have some context on what these functions are for.

2022-11-13 14:37 UTC, ashokponkumar commented on docs/transformers/external/starlark.md
> +* `query()` - Used to prompt Users for input. The function takes two arguments. First is a dictionary with key as variables in the QAEngine's Problem interface and value as value of the variables.
Might be good to move the line starting with `First ...` to the next line.

2022-11-13 14:37 UTC, ashokponkumar commented on docs/transformers/external/starlark.md
> +Move2Kube provides a set a functions in starlark for filesystem based operations.
Doesn't it need to be invoked with `fs.`? Would be better to mention that.

2022-11-13 14:37 UTC, ashokponkumar commented on docs/transformers/external/starlark.md
> +Move2Kube provides a set of variables that can be used in the starlark transformer code.
Would be good to mention that these variables are for exposing values required by the transformer.

2022-11-13 14:37 UTC, ashokponkumar commented on docs/transformers/external/starlark.md
> +Head over to [move2kube-transformers repo](https://github.com/konveyor/move2kube-transformers) for example usages.
Would be good to point to specific starlark based transformer examples, since not all custom transformers use starlark.

2022-11-13 14:37 UTC, ashokponkumar commented
Nice work @kmehant . Have suggested some changes.

2022-11-14 13:34 UTC, ashokponkumar requested changes
Thanks for the updates @kmehant

2022-11-14 13:34 UTC, ashokponkumar commented on docs/transformers/external/starlark.md
> +* `transform()` - It should be implemented to make changes on the input artifacts and output relevant artifacts for the rest of the transformation journey.
Direct links to examples for each of these will help.

2022-11-14 13:34 UTC, ashokponkumar commented on docs/transformers/external/starlark.md
> +Example usage can be found [here](https://github.com/konveyor/move2kube-transformers/blob/2a36d11efb996f2f38cdb3e3ecccfe9378e3a444/cloud-foundry-to-ce-iks-roks/cedockerfile/cedockerfile.star#L52-L63)
this is good, but if we can also put an example in line, it will help.

2022-11-14 13:34 UTC, ashokponkumar commented on docs/transformers/external/starlark.md
> +| `path_rel` | Return relative path | base path as string <br/> target path as string | string
An inline example will help.

2022-11-14 13:34 UTC, ashokponkumar commented on docs/transformers/external/starlark.md
> +
An inline example will help.

2022-11-14 13:34 UTC, ashokponkumar commented on docs/transformers/external/starlark.md
> +
An inline example will help.

2022-11-14 13:34 UTC, ashokponkumar commented on docs/transformers/external/starlark.md
> +| default   | Default input value if the user provide no input | type same as input type |
An in-line json example will help.

2022-11-14 17:09 UTC, kmehant commented
@ashokponkumar I have made the changes!

2022-11-14 17:10 UTC, merged